/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package persistence.project;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Main main = new Main();
        main.serialize();
    }
}
